import './globals.css';
import HamburgerMenu from '@/components/HamburgerMenu/HamburgerMenu';
import FooterComponent from '@/components/Footer/Footer';

export const metadata = {
    title: 'Alto Volcanes',
    description: 'Generated by create next app',
    generator: 'Next.js',
    applicationName: 'WebPage Alto Volcanes',
    authors: [{ name: 'Edgardo Ruotolo Cardozo', url: 'https://crowadvance.com' }],
    creator: 'Edgardo Ruotolo Cardozo',
    publisher: 'Edgardo Ruotolo Cardozo',
};

export default function RootLayout({ children }) {
    return (
        <html lang="es" className="!scroll-smooth">
            <body>
                <HamburgerMenu />
                <main>{children}</main>
                <FooterComponent />
            </body>
        </html>
    );
}
