import './globals.css';
import HamburgerMenu from '@/components/HamburgerMenu/HamburgerMenu';
import FooterComponent from '@/components/Footer/Footer';
import { GoogleAnalytics } from '@next/third-parties/google';

export const metadata = {
    title: 'Alto Volcanes',
    description: 'Generated by create next app',
    generator: 'Next.js',
    applicationName: 'WebPage Alto Volcanes',
    authors: [{ name: 'Edgardo Ruotolo Cardozo', url: 'https://crowadvance.com' }],
    creator: 'Edgardo Ruotolo Cardozo',
    publisher: 'Edgardo Ruotolo Cardozo',
    category: 'Inmobiliaria Sostenible',
    robots: {
        index: true,
        follow: true,
        nocache: true,
        googleBot: {
            index: true,
            follow: true,
            noimageindex: true,
            'max-video-preview': -1,
            'max-image-preview': 'large',
            'max-snippet': -1,
        },
    },
    alternates: {
        canonical: 'https://www.altovolcanes.cl/',
        language: {
            es: '/',
        },
    },
};

export default function RootLayout({ children }) {
    return (
        <html lang="es" className="!scroll-smooth">
            <body>
                <HamburgerMenu />
                <main>{children}</main>
                <FooterComponent />
                <GoogleAnalytics gaId="G-49V3HNY3PG" />
            </body>
        </html>
    );
}
